server:
  port: 8085

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: Task-User-Service
          uri: lb://TASK-USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**,/api/users/**,/

        - id: TASKSERVICE
          uri: lb://TASKSERVICE
          predicates:
            - Path=/api/tasks/**,/tasks/*

        - id: SUBMISSIONSERVICE
          uri: lb://SUBMISSIONSERVICE
          predicates:
            - Path=/api/submissions/**,/submissions/*

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"
