services:
  SubmissionService:
    image: "anshul1321/submissionservice:s4"
    container_name: submissionservice-ms
    ports:
      - "8082:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -easySchedule

  TaskService:
    image: "anshul1321/taskservice:s4"
    container_name: taskservice-ms
    ports:
      - "8083:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -easySchedule

  tsUserRegistry:
    image: "anshul1321/tsUserRegistry:s4"
    container_name: tsUserRegistry-ms
    ports:
      - "8083:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -easySchedule

networks:
  easySchedule:
    driver: "bridge"
